### ISSUE TITLE
npm package not working properly

### ISSUE THREAD

**Issue by kmankan** [Kaliiiiiiiiii-Vinyzu/patchright-nodejs#1]
I think the npm package is not functioning properly.

npm install patchwright works but there is no object 'chromium' in the package.

Also the instructions laid out for installation don't resolve properly
```
❯ npm init patchright@latest
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/create-patchright - Not found
npm error 404
npm error 404  'create-patchright@latest' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
npm error A complete log of this run can be found in: /Users/malin/.npm/_logs/2024-11-03T17_57_28_586Z-debug-0.log
```

**Comment by Vinyzu** [comment]
Fixed.
We had some issues with npm, which is why i had to register an empty patchright package first.
You should now be able to install patchright normally. (Via `npm i patchright`)

Note:
```shell
npm init patchright
```

isnt supported, it was an oversight to include it in the ReadMe. 
Use
```shell
npm i patchright
```
instead. The ReadMe has been updated.
