### ISSUE TITLE
1.49.1 version of Playwright is not published

### ISSUE THREAD

**Issue by egoroof** [Kaliiiiiiiiii-Vinyzu/patchright-nodejs#10]
After manual release of `patchright` 1.49.1 with https://github.com/Kaliiiiiiiiii-Vinyzu/patchright-nodejs/commit/a5b97484c7634041a9baecb41318e4c3acbca267 then automatic release caused by CI (due to [Playwright release 1.49.1](https://github.com/microsoft/playwright/releases/tag/v1.49.1)) failed because `patchright` 1.49.1 already published https://github.com/Kaliiiiiiiiii-Vinyzu/patchright-nodejs/actions/runs/12248124753/job/34167184052

---

Also I think 1.49.1 `patchright` is incorrectly published because `patchright-core` is still 1.49.0:

![image](https://github.com/user-attachments/assets/ef5ab369-46b6-461e-8f40-9705bd0e4c79)

**Comment by Vinyzu** [comment]
https://github.com/Kaliiiiiiiiii-Vinyzu/patchright-nodejs/commit/6148cb4d9d04a7dbf1ab277812fd005640174f6b
