### ISSUE TITLE
Patch Needed: Enhancing Apify Fingerprint Injector Compatibility with Patchright for Complete Worker and DevTools Coverage

### ISSUE THREAD

**Issue by Biswajit96** [Kaliiiiiiiiii-Vinyzu/patchright-nodejs#2]
I've been using Apify's `fingerprint-injector` with Patchright, but it doesn’t override fingerprints in Dedicated Workers, Service Workers, and Shared Workers, leaving these contexts exposed. Also, DevTools detection (https://blog.aepkill.com/demos/devtools-detector/) still shows as "open" when using `fingerprint-injector`.

Is there a patch available to make `fingerprint-injector` fully compatible with Patchright for these cases?

**Comment by Vinyzu** [comment]
`fingerprint-injector` is detectable.
It is out of patchrights scope to patch the fingerprints in the Workers. Indeed, you have to patch chromium source / work with os hooks to patch this issue. I generally dont recommend to use `fingerprint-injector` (or other navigator fingerprint injectors) if you have issues with detection.

However, i do wonder why it detects the DevTools. I could not reproduce this with normal scripts, so i think this is also an issue with `fingerprint-injector`. If you manage to reproduce this leak with a "normal" (non js altering) script, open a seperate issue.

**Comment by noodleman420** [comment]
@Biswajit96 Just curious do you have any example script of you using fingerprint-injector?

I am getting `this.context is not a function` but not quite sure why

**Comment by Mkopl360** [comment]
sure hope its help.
```
import { chromium } from "patchright";
import { FingerprintGenerator } from 'fingerprint-generator';
import { FingerprintInjector } from 'fingerprint-injector';
     const browser = await chromium.launch({
          headless: false, // Set to true for production
          ignoreDefaultArgs: [
               "--disable-crash-reporter",
               "--disable-crashpad-for-testing",
               "--disable-gpu-watchdog",
          ],
          args: [
               "--no-sandbox",
               "--disable-blink-features=AutomationControlled",
               "--disable-audio-output",
               //"--bot-profile=chrome135_mac_arm64.enc",
          ],
     });
  const fingerprintInjector = new FingerprintInjector();
     const context = await browser.newContext({
          userAgent: fingerprint.fingerprint.navigator.userAgent,
          locale: fingerprint.fingerprint.navigator.language,
          viewport: {
               width: fingerprint.fingerprint.screen.width,
               height: fingerprint.fingerprint.screen.height
          }
     });
     console.log(JSON.stringify(fingerprint, null, 2));
     await fingerprintInjector.attachFingerprintToPlaywright(context, fingerprint);
```
